name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@tonytore'

      - run: npm ci
      - run: npm run build

      # safety lock
      - name: Verify tag matches package.json
        run: |
          TAG=${GITHUB_REF_NAME#v}
          PKG=$(node -p "require('./package.json').version")
          if [ "$TAG" != "$PKG" ]; then
            echo "Tag $TAG does not match package.json $PKG"
            exit 1
          fi

      - run: cp package.json build/package.json

      - run: npm publish
        working-directory: build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
